"""
View Enhancer using FLUX.2 Klein 9B (Distilled)

This module enhances images generated by view_generator.py using the FLUX.2 Klein 9B
distilled model with only 4 inference steps.

For each sample, the enhancement process:
1. Loads the generated image from view_generator.py
2. Loads the corresponding reference image
3. Applies matting to both images (converts backgrounds to white)
4. Uses FLUX.2 Klein to enhance/refine the image
5. Saves the enhanced output as target_image_fk.png
"""

import argparse
import gc
import json
import random
import sys
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Union

import numpy as np
import torch
from PIL import Image

from diffusers import Flux2KleinPipeline

from hairport.core.bg_remover import BackgroundRemover
from hairport.config import get_config

# ============================================================================
# Configuration — reads from centralized config at call time
# ============================================================================

def _bg_color() -> tuple:
    """Background color from config (lazy)."""
    return tuple(get_config().enhance_view.bg_color)

# Keep a module-level name for static analysis; runtime call-sites use _bg_color().
BG_COLOR = (255, 255, 255)

# ============================================================================
# Utility Functions
# ============================================================================

def flush_gpu_memory():
    """Clear GPU memory cache."""
    gc.collect()
    torch.cuda.empty_cache()


def apply_white_background(image: Image.Image, mask: Image.Image = None) -> Image.Image:
    """
    Apply white background to an image.
    
    Args:
        image: The image (RGB or RGBA). If RGBA, uses embedded alpha. If RGB, uses mask.
        mask: Optional alpha mask (grayscale). Used only if image is RGB.
        
    Returns:
        RGB image with white background
    """
    # Get or create RGBA image with proper alpha
    if image.mode == "RGBA":
        # Use the embedded alpha channel directly
        rgba_image = image.copy()
    else:
        # Convert to RGBA (will have full opacity by default)
        rgba_image = image.convert("RGBA")
        # Apply mask as alpha if provided
        if mask is not None:
            mask_l = mask.convert("L") if mask.mode != "L" else mask
            if mask_l.size != rgba_image.size:
                mask_l = mask_l.resize(rgba_image.size, Image.Resampling.LANCZOS)
            rgba_image.putalpha(mask_l)
    
    # Create white background
    white_bg = Image.new("RGBA", rgba_image.size, (*_bg_color(), 255))
    
    # Composite image onto white background
    result = Image.alpha_composite(white_bg, rgba_image)
    
    # Convert to RGB to ensure no alpha channel in output
    final = result.convert("RGB")
    
    return final


def preprocess_image_with_matting(
    image: Union[str, Path, Image.Image],
    bg_remover: BackgroundRemover,
    target_size: Tuple[int, int] = (1024, 1024),
) -> Image.Image:
    """
    Apply matting to an image and convert background to white.
    
    Args:
        image: Input image (path or PIL Image)
        bg_remover: BackgroundRemover instance
        target_size: Target size (width, height)
        
    Returns:
        Processed image with white background
    """
    # Load image if path
    if isinstance(image, (str, Path)):
        image = Image.open(image).convert("RGB")
    elif image.mode != "RGB":
        image = image.convert("RGB")
    
    # Remove background (returns RGBA image and mask)
    foreground, mask = bg_remover.remove_background(image)
    
    # Apply white background
    result = apply_white_background(foreground, mask)
    
    # Resize to target size if needed
    if result.size != target_size:
        result = result.resize(target_size, Image.Resampling.LANCZOS)
    
    result = result.convert("RGB")
    return result


def compute_output_dimensions(
    image: Image.Image,
    max_size: int | None = None,
) -> Tuple[int, int]:
    """
    Compute output dimensions maintaining aspect ratio with both sides as multiples of 8.
    
    Args:
        image: Input image
        max_size: Maximum dimension size
        
    Returns:
        Tuple of (width, height)
    """
    if max_size is None:
        max_size = get_config().enhance_view.max_image_size
    img_width, img_height = image.size
    aspect_ratio = img_width / img_height
    
    if aspect_ratio >= 1:  # Landscape or square
        new_width = max_size
        new_height = int(max_size / aspect_ratio)
    else:  # Portrait
        new_height = max_size
        new_width = int(max_size * aspect_ratio)
    
    # Round to nearest multiple of 8
    new_width = round(new_width / 8) * 8
    new_height = round(new_height / 8) * 8
    
    # Ensure within valid range
    new_width = max(256, min(max_size, new_width))
    new_height = max(256, min(max_size, new_height))
    
    return new_width, new_height


def get_foreground_bbox(mask: Image.Image) -> Tuple[int, int, int, int]:
    """
    Get the bounding box of the foreground from a mask.
    
    Args:
        mask: Grayscale mask where foreground is white (255)
        
    Returns:
        Tuple of (left, top, right, bottom) bounding box
    """
    # Ensure mask is in L mode
    if mask.mode != "L":
        mask = mask.convert("L")
    
    mask_array = np.array(mask)
    
    # Find non-zero (foreground) pixels
    rows = np.any(mask_array > 127, axis=1)
    cols = np.any(mask_array > 127, axis=0)
    
    if not np.any(rows) or not np.any(cols):
        # No foreground found, return full image
        return (0, 0, mask.width, mask.height)
    
    top, bottom = np.where(rows)[0][[0, -1]]
    left, right = np.where(cols)[0][[0, -1]]
    
    return (int(left), int(top), int(right) + 1, int(bottom) + 1)


def crop_and_center_foreground(
    image: Image.Image,
    mask: Image.Image,
    padding_ratio: float = 0.05,
    target_size: Tuple[int, int] = (1024, 1024),
) -> Tuple[Image.Image, Dict]:
    """
    Crop the foreground from an image, center it with padding, and resize to target size.
    
    The foreground will occupy (1 - 2*padding_ratio) of the output canvas in the 
    constraining dimension, ensuring consistent padding regardless of foreground size.
    
    Args:
        image: Input RGB image
        mask: Foreground mask (white = foreground)
        padding_ratio: Padding ratio around the foreground in OUTPUT space (0.1 = 10% on each side)
        target_size: Target output size (width, height)
        
    Returns:
        Tuple of (cropped_centered_image, crop_info_dict)
        crop_info_dict contains information needed to uncrop later
    """
    # Ensure image is RGB
    if image.mode != "RGB":
        image = image.convert("RGB")
    
    # Get foreground bounding box
    bbox = get_foreground_bbox(mask)
    left, top, right, bottom = bbox
    
    fg_width = right - left
    fg_height = bottom - top
    
    img_width, img_height = image.size
    target_width, target_height = target_size
    
    # Calculate scale so that foreground occupies (1 - 2*padding_ratio) of target
    # e.g., with padding_ratio=0.1, foreground should be 80% of target in constraining dimension
    desired_fg_ratio = 1.0 - 2.0 * padding_ratio
    scale_x = (target_width * desired_fg_ratio) / fg_width
    scale_y = (target_height * desired_fg_ratio) / fg_height
    scale = min(scale_x, scale_y)
    
    # Calculate the size of foreground after scaling
    scaled_fg_width = int(fg_width * scale)
    scaled_fg_height = int(fg_height * scale)
    
    # Calculate paste position to center foreground in target canvas
    paste_x = (target_width - scaled_fg_width) // 2
    paste_y = (target_height - scaled_fg_height) // 2
    
    # Crop just the foreground region from source image
    cropped_fg = image.crop((left, top, right, bottom))
    
    # Resize foreground to target scale
    resized_fg = cropped_fg.resize((scaled_fg_width, scaled_fg_height), Image.Resampling.LANCZOS)
    
    # Create white background canvas and paste centered foreground
    canvas = Image.new("RGB", target_size, _bg_color())
    canvas.paste(resized_fg, (paste_x, paste_y))
    
    # Store crop info for later uncropping
    crop_info = {
        "original_size": (img_width, img_height),
        "foreground_bbox": (left, top, right, bottom),  # Original foreground location
        "scale": scale,
        "paste_offset": (paste_x, paste_y),
        "scaled_fg_size": (scaled_fg_width, scaled_fg_height),
        "target_size": target_size,
    }
    
    return canvas, crop_info


def uncrop_to_original(
    enhanced_image: Image.Image,
    crop_info: Dict,
) -> Image.Image:
    """
    Uncrop the enhanced image back to the original image space.
    
    This function maps the entire enhanced canvas (including padding areas where
    the enhancement may have extended content) back to original image space.
    
    Args:
        enhanced_image: The enhanced image (target_size)
        crop_info: Dictionary with crop information from crop_and_center_foreground
        
    Returns:
        Image placed back in original spatial dimensions with white background
    """
    paste_x, paste_y = crop_info["paste_offset"]
    scale = crop_info["scale"]
    left, top, right, bottom = crop_info["foreground_bbox"]
    original_width, original_height = crop_info["original_size"]
    target_width, target_height = crop_info["target_size"]
    
    # Calculate what region in original space the entire canvas represents
    # Canvas point (0,0) maps to original point (left - paste_x/scale, top - paste_y/scale)
    canvas_origin_in_orig_x = left - paste_x / scale
    canvas_origin_in_orig_y = top - paste_y / scale
    
    # The full canvas size in original space
    canvas_size_in_orig_x = target_width / scale
    canvas_size_in_orig_y = target_height / scale
    
    # Resize entire enhanced canvas to original scale
    orig_scale_width = int(round(canvas_size_in_orig_x))
    orig_scale_height = int(round(canvas_size_in_orig_y))
    
    resized_canvas = enhanced_image.resize(
        (orig_scale_width, orig_scale_height), 
        Image.Resampling.LANCZOS
    )
    
    # Create output image with white background
    output = Image.new("RGB", (original_width, original_height), _bg_color())
    
    # Calculate paste position in original space (may be negative or extend beyond bounds)
    paste_orig_x = int(round(canvas_origin_in_orig_x))
    paste_orig_y = int(round(canvas_origin_in_orig_y))
    
    # Handle boundary clipping - determine which part of resized_canvas to copy
    # and where to paste it in the output
    src_left = max(0, -paste_orig_x)
    src_top = max(0, -paste_orig_y)
    src_right = min(orig_scale_width, original_width - paste_orig_x)
    src_bottom = min(orig_scale_height, original_height - paste_orig_y)
    
    dst_left = max(0, paste_orig_x)
    dst_top = max(0, paste_orig_y)
    
    # Extract and paste the valid region
    if src_right > src_left and src_bottom > src_top:
        region = resized_canvas.crop((src_left, src_top, src_right, src_bottom))
        output.paste(region, (dst_left, dst_top))
    
    return output


# ============================================================================
# View Enhancer Class
# ============================================================================

class ViewEnhancer:
    """
    Enhancer for images generated by view_generator.py using FLUX.2 Klein 9B.
    """
    
    def __init__(
        self,
        model_id: str | None = None,
        device: str | None = None,
        dtype: torch.dtype = torch.bfloat16,
        load_pipeline: bool = True,
    ):
        """
        Initialize the ViewEnhancer.
        
        Args:
            model_id: HuggingFace model repository ID
            device: Device to run the model on
            dtype: Data type for model weights
            load_pipeline: Whether to load the pipeline immediately
        """
        cfg = get_config()
        self.model_id = model_id or cfg.models.flux_klein
        self.device = device or cfg.device
        self.dtype = dtype
        self.pipe = None
        self.bg_remover = None
        
        if load_pipeline:
            self.load_pipeline()
    
    def load_pipeline(self):
        """Load the FLUX.2 Klein pipeline and background remover."""
        self.pipe = Flux2KleinPipeline.from_pretrained(
            self.model_id,
            torch_dtype=self.dtype,
        )
        self.pipe.to(self.device)
        
        # Initialize background remover
        self.bg_remover = BackgroundRemover(device=self.device)
    
    def enhance_image_phase1(
        self,
        generated_image: Union[str, Path, Image.Image],
        prompt: Optional[str] = None,
        num_inference_steps: int | None = None,
        guidance_scale: float | None = None,
        seed: int = -1,
        width: Optional[int] = None,
        height: Optional[int] = None,
    ) -> Image.Image:
        """
        Phase 1: Enhance a generated image to fix artifacts and improve realism.
        
        Note: This method expects the image to already be centered/preprocessed.
        The centering is done in enhance_image() before calling this method.
        
        Args:
            generated_image: The preprocessed/centered image
            prompt: Custom prompt (uses FIRST_PHASE_PROMPT if None)
            num_inference_steps: Number of inference steps (default: 4 for distilled)
            guidance_scale: Guidance scale (default: 1.0 for distilled)
            seed: Random seed (-1 for random)
            width: Output width (auto-computed if None)
            height: Output height (auto-computed if None)
            
        Returns:
            Enhanced image (Phase 1 output)
        """
        if self.pipe is None:
            self.load_pipeline()

        ev = get_config().enhance_view
        if num_inference_steps is None:
            num_inference_steps = ev.num_inference_steps
        if guidance_scale is None:
            guidance_scale = ev.guidance_scale
        
        # Load image if path
        if isinstance(generated_image, (str, Path)):
            generated_image = Image.open(generated_image).convert("RGB")
        
        # Compute dimensions if not provided
        if width is None or height is None:
            width, height = compute_output_dimensions(generated_image)
        
        target_size = (width, height)
        
        # Apply matting to the image (convert background to white)
        generated_matted = preprocess_image_with_matting(
            generated_image,
            self.bg_remover,
            target_size=target_size,
        )
        
        # Single image input for Phase 1
        image_list = [generated_matted]
        
        # Use Phase 1 prompt if not provided
        if prompt is None:
            prompt = get_config().prompts.enhance_first_phase
        
        # Set up generator for reproducibility
        if seed != -1 and isinstance(seed, int):
            generator = torch.Generator(device=self.device).manual_seed(seed)
        else:
            seed = random.randint(0, np.iinfo(np.int32).max)
            generator = torch.Generator(device=self.device).manual_seed(seed)
        
        # Run the pipeline
        result = self.pipe(
            prompt=prompt,
            image=image_list,
            height=height,
            width=width,
            num_inference_steps=num_inference_steps,
            guidance_scale=guidance_scale,
            generator=generator,
        )
        
        enhanced_image = result.images[0]
        
        # Ensure output is RGB with white background
        if enhanced_image.mode != "RGB":
            enhanced_image = enhanced_image.convert("RGB")
        
        # Apply matting to ensure white background
        enhanced_image = preprocess_image_with_matting(
            enhanced_image,
            self.bg_remover,
            target_size=target_size,
        )
        
        return enhanced_image
    
    def enhance_image_phase2(
        self,
        phase1_image: Union[str, Path, Image.Image],
        reference_image: Union[str, Path, Image.Image],
        prompt: Optional[str] = None,
        num_inference_steps: int | None = None,
        guidance_scale: float | None = None,
        seed: int = -1,
        width: Optional[int] = None,
        height: Optional[int] = None,
    ) -> Image.Image:
        """
        Phase 2: Enhance the Phase 1 output using reference image for identity matching.
        
        Args:
            phase1_image: The output from Phase 1
            reference_image: The original reference image for identity
            prompt: Custom prompt (uses SECOND_PHASE_PROMPT if None)
            num_inference_steps: Number of inference steps (default: 4 for distilled)
            guidance_scale: Guidance scale (default: 1.0 for distilled)
            seed: Random seed (-1 for random)
            width: Output width (auto-computed if None)
            height: Output height (auto-computed if None)
            
        Returns:
            Enhanced image (Phase 2 / final output)
        """
        if self.pipe is None:
            self.load_pipeline()

        ev = get_config().enhance_view
        if num_inference_steps is None:
            num_inference_steps = ev.num_inference_steps
        if guidance_scale is None:
            guidance_scale = ev.guidance_scale

        # Load images if paths
        if isinstance(phase1_image, (str, Path)):
            phase1_image = Image.open(phase1_image).convert("RGB")
        if isinstance(reference_image, (str, Path)):
            reference_image = Image.open(reference_image).convert("RGB")
        
        # Compute dimensions if not provided
        if width is None or height is None:
            width, height = compute_output_dimensions(phase1_image)
        
        # Apply matting to both images (convert background to white)
        phase1_matted = preprocess_image_with_matting(
            phase1_image,
            self.bg_remover,
            target_size=(width, height),
        )
        
        reference_matted = preprocess_image_with_matting(
            reference_image,
            self.bg_remover,
            target_size=(width, height),
        )
        
        # Prepare image list for FLUX.2 Klein (Phase 1 output + reference)
        image_list = [phase1_matted, reference_matted]
        
        # Use Phase 2 prompt if not provided
        if prompt is None:
            prompt = get_config().prompts.enhance_second_phase
        
        # Set up generator for reproducibility
        if seed != -1 and isinstance(seed, int):
            generator = torch.Generator(device=self.device).manual_seed(seed)
        else:
            seed = random.randint(0, np.iinfo(np.int32).max)
            generator = torch.Generator(device=self.device).manual_seed(seed)
        
        # Run the pipeline
        result = self.pipe(
            prompt=prompt,
            image=image_list,
            height=height,
            width=width,
            num_inference_steps=num_inference_steps,
            guidance_scale=guidance_scale,
            generator=generator,
        )
        
        enhanced_image = result.images[0]
        
        return enhanced_image
    
    def enhance_image(
        self,
        generated_image: Union[str, Path, Image.Image],
        reference_image: Union[str, Path, Image.Image],
        prompt_phase1: Optional[str] = None,
        prompt_phase2: Optional[str] = None,
        num_inference_steps: int | None = None,
        guidance_scale: float | None = None,
        seed: int = -1,
        width: Optional[int] = None,
        height: Optional[int] = None,
        padding_ratio: float | None = None,
    ) -> Tuple[Image.Image, Image.Image, Dict]:
        """
        Two-phase image enhancement process.
        
        Phase 1: Enhance the generated image to fix artifacts and improve realism.
        Phase 2: Use the Phase 1 output with reference image for identity matching.
        
        Args:
            generated_image: The image generated by view_generator.py
            reference_image: The original reference image for identity
            prompt_phase1: Custom prompt for Phase 1 (uses FIRST_PHASE_PROMPT if None)
            prompt_phase2: Custom prompt for Phase 2 (uses SECOND_PHASE_PROMPT if None)
            num_inference_steps: Number of inference steps (default: 4 for distilled)
            guidance_scale: Guidance scale (default: 1.0 for distilled)
            seed: Random seed (-1 for random)
            width: Output width (auto-computed if None)
            height: Output height (auto-computed if None)
            padding_ratio: Padding ratio for foreground centering (default: 0.1 = 10%)
            
        Returns:
            Tuple of (phase1_image, phase2_image, crop_info)
        """
        if self.pipe is None:
            self.load_pipeline()

        ev = get_config().enhance_view
        if num_inference_steps is None:
            num_inference_steps = ev.num_inference_steps
        if guidance_scale is None:
            guidance_scale = ev.guidance_scale
        if padding_ratio is None:
            padding_ratio = ev.padding_ratio
        
        # Load images if paths
        if isinstance(generated_image, (str, Path)):
            generated_image = Image.open(generated_image).convert("RGB")
        if isinstance(reference_image, (str, Path)):
            reference_image = Image.open(reference_image).convert("RGB")
        
        # Store TRUE original size before any processing
        true_original_size = generated_image.size
        
        # Compute dimensions if not provided
        if width is None or height is None:
            width, height = compute_output_dimensions(generated_image)
        
        target_size = (width, height)
        
        # Preprocessing: Apply matting in ORIGINAL coordinate space first (no resize)
        # This ensures crop_info is computed in original space for correct inverse transformation
        foreground_original, original_mask = self.bg_remover.remove_background(generated_image)
        generated_matted_original = apply_white_background(foreground_original, original_mask)
        
        # Crop and center foreground with padding - computed in ORIGINAL coordinate space
        # The crop_info will have original_size = true_original_size
        centered_image, crop_info = crop_and_center_foreground(
            generated_matted_original,
            original_mask,
            padding_ratio=padding_ratio,
            target_size=target_size,
        )
        
        # Apply matting to the centered image (already at target_size)
        centered_image = preprocess_image_with_matting(
            centered_image,
            self.bg_remover,
            target_size=target_size,
        )
        
        # Phase 1: Single image enhancement with centered image
        phase1_result = self.enhance_image_phase1(
            generated_image=centered_image,
            prompt=prompt_phase1,
            num_inference_steps=num_inference_steps,
            guidance_scale=guidance_scale,
            seed=seed,
            width=width,
            height=height,
        )

        phase1_result_copy = phase1_result.convert("RGB")
        # Phase 2: Identity-guided enhancement
        phase2_result = self.enhance_image_phase2(
            phase1_image=phase1_result_copy,
            reference_image=reference_image,
            prompt=prompt_phase2,
            num_inference_steps=num_inference_steps,
            guidance_scale=guidance_scale,
            seed=seed,
            width=width,
            height=height,
        )
        
        return phase1_result, phase2_result, crop_info
    
    def unload(self):
        """Unload pipeline and free GPU memory."""
        if self.pipe is not None:
            del self.pipe
            self.pipe = None
        if self.bg_remover is not None:
            del self.bg_remover
            self.bg_remover = None
        flush_gpu_memory()


# ============================================================================
# Batch Processing Functions
# ============================================================================

def process_view_aligned_folder(
    folder_path: Path,
    data_dir: Path,
    bald_version: str = "w_seg",
    seed: int = -1,
    enhancer: Optional[ViewEnhancer] = None,
) -> bool:
    """
    Process a single view-aligned folder to enhance the generated image.
    
    Args:
        folder_path: Path to the view-aligned folder
        data_dir: Root data directory
        bald_version: Bald version mode ("w_seg", "wo_seg")
        seed: Random seed for enhancement
        enhancer: ViewEnhancer instance (creates new one if None)
        
    Returns:
        True if successful, False otherwise
    """
    # Define paths
    input_image_path = folder_path / "alignment" / "target_image.png"
    phase1_output_path = folder_path / "alignment" / "target_image_phase_1.png"
    final_output_path = folder_path / "alignment" / "target_image_phase_2.png"
    folder_name = folder_path.name
    
    # Check if input exists
    if not input_image_path.exists():
        return False
    
    # Skip if already processed (check final output)
    # if phase1_output_path.exists():
    #     return False
    
    # Parse folder name to extract target_id
    # Format: {target_id}_to_{source_id}
    parts = folder_name.split("_to_")
    if len(parts) != 2:
        return False
    
    target_id, source_id = parts
    
    # Determine reference image path based on dataset
    dataset_name = Path(data_dir).name
    if dataset_name == "celeba_reduced":
        image_folder = "image_outpainted"
    else:
        image_folder = "hair_aligned_image"
    
    reference_image_path = data_dir / image_folder / f"{target_id}.png"
    
    if not reference_image_path.exists():
        return False
    
    print(f"Input: {input_image_path}")
    print(f"Reference: {reference_image_path}")
    
    try:
        # Create enhancer if not provided
        should_unload = False
        if enhancer is None:
            enhancer = ViewEnhancer(load_pipeline=True)
            should_unload = True
        
        # Run two-phase enhancement
        phase1_image, phase2_image, crop_info = enhancer.enhance_image(
            generated_image=str(input_image_path),
            reference_image=str(reference_image_path),
            seed=seed,
        )
        
        # Save raw Phase 1 output (before inverse transformation)
        raw_output_path = folder_path / "alignment" / "target_image_phase_1_raw.png"
        raw_output_path.parent.mkdir(parents=True, exist_ok=True)
        if phase1_image.mode != "RGB":
            phase1_image_rgb = phase1_image.convert("RGB")
        else:
            phase1_image_rgb = phase1_image
        phase1_image_rgb.save(raw_output_path)
        print(f"Phase 1 raw output: {raw_output_path}")
        
        # Apply inverse transformation to restore original spatial dimensions
        phase1_uncropped = uncrop_to_original(phase1_image, crop_info)
        phase2_uncropped = uncrop_to_original(phase2_image, crop_info)
        
        # Save outputs - ensure RGB mode for white background (no transparency)
        phase1_output_path.parent.mkdir(parents=True, exist_ok=True)
        if phase1_uncropped.mode != "RGB":
            phase1_uncropped = phase1_uncropped.convert("RGB")
        phase1_uncropped.save(phase1_output_path)
        print(f"Phase 1 output: {phase1_output_path}")
        
        if phase2_uncropped.mode != "RGB":
            phase2_uncropped = phase2_uncropped.convert("RGB")
        phase2_uncropped.save(final_output_path)
        print(f"Phase 2 output: {final_output_path}")
        
        if should_unload:
            enhancer.unload()
        
        return True
        
    except Exception as e:
        print(f"Error: {folder_name}: {e}")
        return False


def enhance_view_ig2mv(
    generated_image: Union[str, Path, Image.Image],
    reference_image: Union[str, Path, Image.Image],
    prompt_phase1: Optional[str] = None,
    prompt_phase2: Optional[str] = None,
    seed: int = -1,
    num_inference_steps: int | None = None,
    guidance_scale: float | None = None,
    padding_ratio: float | None = None,
    enhancer: Optional[ViewEnhancer] = None,
) -> Tuple[Image.Image, Image.Image, Dict]:
    """
    Convenience function for quick two-phase enhancement.
    
    Args:
        generated_image: The image generated by view_generator.py
        reference_image: The original reference image
        prompt_phase1: Custom prompt for Phase 1 (uses default if None)
        prompt_phase2: Custom prompt for Phase 2 (uses default if None)
        seed: Random seed
        num_inference_steps: Number of inference steps
        guidance_scale: Guidance scale
        padding_ratio: Padding ratio for foreground centering (default: 0.1 = 10%)
        enhancer: ViewEnhancer instance (creates new one if None)
        
    Returns:
        Tuple of (phase1_image, phase2_image, crop_info)
    """
    should_unload = False
    if enhancer is None:
        enhancer = ViewEnhancer(load_pipeline=True)
        should_unload = True
    
    try:
        result = enhancer.enhance_image(
            generated_image=generated_image,
            reference_image=reference_image,
            prompt_phase1=prompt_phase1,
            prompt_phase2=prompt_phase2,
            seed=seed,
            num_inference_steps=num_inference_steps,
            guidance_scale=guidance_scale,
            padding_ratio=padding_ratio,
        )
        return result
    finally:
        if should_unload:
            enhancer.unload()


# ============================================================================
# Main Entry Point
# ============================================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Enhance images generated by view_generator.py using FLUX.2 Klein 9B"
    )
    parser.add_argument(
        "--data_dir",
        type=str,
        default="outputs/",
        help="Root data directory containing view_aligned folders"
    )
    parser.add_argument(
        "--shape_provider",
        type=str,
        default="hi3dgen",
        choices=["hunyuan", "hi3dgen", "direct3d_s2"],
        help="Shape provider used in view alignment"
    )
    parser.add_argument(
        "--texture_provider",
        type=str,
        default="mvadapter",
        choices=["hunyuan", "mvadapter"],
        help="Texture provider used in view alignment"
    )
    parser.add_argument(
        "--bald_version",
        default="w_seg",
        type=str,
        choices=["w_seg", "wo_seg", "all"],
        help="Bald version mode"
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=-1,
        help="Random seed (-1 for random)"
    )
    parser.add_argument(
        "--num_inference_steps",
        type=int,
        default=None,
        help="Number of inference steps"
    )
    parser.add_argument(
        "--guidance_scale",
        type=float,
        default=None,
        help="Guidance scale"
    )
    args = parser.parse_args()
    
    # Construct view_aligned directory path
    data_dir = Path(args.data_dir)
    provider_subdir = f"shape_{args.shape_provider}__texture_{args.texture_provider}"
    view_aligned_dir = data_dir / "view_aligned" / provider_subdir
    
    if not view_aligned_dir.exists():
        print(f"View aligned directory not found: {view_aligned_dir}")
        exit(1)
    
    # Get all subdirectories
    all_folders = [f for f in view_aligned_dir.iterdir() if f.is_dir()]
    
    # Seed random by timestamp and shuffle folders
    timestamp_seed = int(time.time())
    random.seed(timestamp_seed)
    random.shuffle(all_folders)
    print(f"Processing {len(all_folders)} folders (seed: {timestamp_seed})")
    
    # Create a single ViewEnhancer instance to reuse across all folders
    enhancer = ViewEnhancer(load_pipeline=True)
    
    # Process each folder
    processed_count = 0
    skipped_count = 0
    error_count = 0
    
    # Determine bald versions to process
    if args.bald_version == "all":
        bald_versions = ["w_seg", "wo_seg"]
    else:
        bald_versions = [args.bald_version]
    
    try:
        for bald_version in bald_versions:
            for i, folder in enumerate(all_folders, 1):
                # Skip if folder name is not sample_140_to_bale_1
                # if folder.name != "sample_140_to_bale_1":
                #     print(f"\n[{i}/{len(all_folders)}] {folder.name} - skipping (not sample_140_to_bale_1)")
                #     skipped_count += 1
                #     continue
                
                # Check if already processed
                output_path = folder / "alignment" / "target_image_phase_1.png"
                if output_path.exists():
                    print(f"\n[{i}/{len(all_folders)}] {output_path} - already processed, skipping")
                    skipped_count += 1
                    continue
                
                # Check if input exists
                input_path = folder / "alignment" / "target_image.png"
                if not input_path.exists():
                    print(f"\n[{i}/{len(all_folders)}] {input_path} - input not found, skipping")
                    skipped_count += 1
                    continue
                
                print(f"\n[{i}/{len(all_folders)}] {folder.name} ({bald_version})")
                
                result = process_view_aligned_folder(
                    folder_path=folder,
                    data_dir=data_dir,
                    bald_version=bald_version,
                    seed=args.seed,
                    enhancer=enhancer,
                )
                
                if result is True:
                    processed_count += 1
                else:
                    error_count += 1
                    
    finally:
        enhancer.unload()
    
    print(f"\nDone: {processed_count} enhanced, {skipped_count} skipped, {error_count} errors")
